---
- name: add group "tomcat"
  group: name={{tomcat_group}}

- name: add user "tomcat"
  user: name={{tomcat_user}} group={{tomcat_group}} home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.61/bin/apache-tomcat-7.0.61.tar.gz dest=/opt/apache-tomcat-7.0.61.tar.gz

- name: Extract archive
  command: chdir=/usr/share /usr/bin/tar xvf /opt/apache-tomcat-7.0.61.tar.gz -C /opt/ creates=/opt/apache-tomcat-7.0.61

- name: Symlink install directory
  file: src=/opt/apache-tomcat-7.0.61 path=/usr/share/tomcat state=link

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Configure Tomcat server
  template: src=server.xml dest=/usr/share/tomcat/conf/

  
- name: Create  sample directory
  file: 
    path: "/opt/apache-tomcat-7.0.61/webapps/samples"
    state: directory
    mode: 0777
  become: true
  

- name: copy war file
  copy: src=./target/LoginWebApp-1.war dest=/opt/apache-tomcat-7.0.61/webapps/


  notify: restart tomcat
  

- name: Change ownership
  file:
    path: /opt/apache-tomcat-7.0.61
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory

- name: Copy Tomcat service from local to remote
  copy:
      src: tomcat.service
      dest: /etc/systemd/system/
      mode: 0755

- name: Start and enable Tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: true
      daemon_reload: true

- name: wait for tomcat to start
  wait_for: port={{http_port}}
